# Generated by Django 2.2.10 on 2021-02-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_title', models.CharField(max_length=100, verbose_name='Название опроса')),
                ('interview_description', models.TextField(verbose_name='Описание опроса')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300, verbose_name='Текст вопроса')),
                ('answer_type', models.NullBooleanField(verbose_name='Тип вопроса')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='answer_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=300, verbose_name='Текст ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.question')),
            ],
        ),
    ]
