# Generated by Django 2.2.10 on 2021-02-10 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 15, 19, 16, 295010, tzinfo=utc), verbose_name='Дата окончания опроса'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 15, 19, 16, 295010, tzinfo=utc), editable=False, verbose_name='Дата начала опроса'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_description',
            field=models.TextField(blank=True, verbose_name='Описание опроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Тип вопроса'),
        ),
    ]
