# Generated by Django 2.2.10 on 2021-02-10 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_auto_20210210_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата начала опроса'),
        ),
    ]
