# Generated by Django 2.2.10 on 2021-02-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_auto_20210210_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_options',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Question'),
        ),
    ]
