# Generated by Django 2.2.10 on 2021-02-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_auto_20210210_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='answer_options',
            new_name='Answer_option',
        ),
        migrations.AlterField(
            model_name='answer_option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Question'),
        ),
    ]
