# Generated by Django 2.2.10 on 2021-02-13 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0005_auto_20210210_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer_option',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='answer_option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Тип вопроса (0-ответ текстом, 1-выбор варианта, 2-выбор нескольких вариантов)'),
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('interview_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата опроса')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Interview')),
            ],
            options={
                'verbose_name': 'Результат опроса',
                'verbose_name_plural': 'Результаты опросов',
            },
        ),
    ]
