# Generated by Django 2.2.10 on 2021-02-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0006_auto_20210213_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Question'),
        ),
        migrations.CreateModel(
            name='Result_a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField(verbose_name='Номер вопроса')),
                ('answer', models.TextField(verbose_name='Ответ пользователя')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Result')),
            ],
        ),
    ]
