# Generated by Django 2.2.10 on 2021-02-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0007_auto_20210213_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer_option',
            new_name='AnswerOption',
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Question'),
        ),
        migrations.AlterField(
            model_name='result_a',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Result'),
        ),
    ]
