# Generated by Django 2.2.10 on 2021-02-14 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0008_auto_20210214_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_type',
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Question'),
        ),
        migrations.AlterField(
            model_name='result_a',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Result'),
        ),
    ]
