# Generated by Django 2.2.10 on 2021-02-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0011_auto_20210214_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result_a',
            new_name='ResultA',
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Question'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resulta',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Result'),
        ),
    ]
