# Generated by Django 2.2.10 on 2021-02-16 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0013_auto_20210216_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='quest.Question'),
        ),
        migrations.AlterField(
            model_name='result',
            name='interview',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='quest.Interview'),
        ),
        migrations.AlterField(
            model_name='result',
            name='interview_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата опроса'),
        ),
        migrations.AlterField(
            model_name='result',
            name='user_id',
            field=models.PositiveIntegerField(editable=False, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='resulta',
            name='answer',
            field=models.TextField(editable=False, verbose_name='Ответ пользователя'),
        ),
        migrations.AlterField(
            model_name='resulta',
            name='question_number',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='Номер вопроса'),
        ),
        migrations.AlterField(
            model_name='resulta',
            name='result',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='quest.Result'),
        ),
    ]
