# Generated by Django 2.2.10 on 2021-02-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0016_auto_20210216_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='quest.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ответ текстом'), (2, 'Выбор одного варианта ответа'), (3, 'Выбор нескольких вариантов ответов')], default=1, verbose_name='Тип вопроса (1-ответ текстом, 2-выбор варианта, 3-выбор нескольких вариантов)'),
        ),
        migrations.AlterField(
            model_name='resulta',
            name='result',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='quest.Result'),
        ),
    ]
