# Generated by Django 2.2.10 on 2021-02-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0020_auto_20210216_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultA',
            new_name='ResultAnswer',
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='quest.Question'),
        ),
        migrations.AlterField(
            model_name='resultanswer',
            name='question_number',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='quest.Question'),
        ),
        migrations.AlterField(
            model_name='resultanswer',
            name='result',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='quest.Result'),
        ),
    ]
